### PR TITLE
Add an example way to secure the JMX endpoint configuration for monitoring

### PR DESCRIPTION
**Pull request by purbon**
This PR adds a directory showing how to secure the Kafka JMX monitoring endpoint. This example is build using SSL and authentication.

### CODE REVIEW

**Comment by purbon** [comment]
@Dabz thoughts?

**Comment by Dabz** [comment]
I do not know much about JMX security, but it looks great to me.
The only comment I would have are:

- We should probably rely on CP 5.5 instead of CP 5.4
- We should probably keep the configuration files as short as possible instead of relying on the verbose default one (e.g. https://github.com/Dabz/kafka-security-playbook/blob/master/kerberos/kafka/server.properties)
- A quick README would be nice (for the uninitiated like me ;) )

**Comment by purbon** [comment]
I dont know what do you mean with 

```
We should probably keep the configuration files as short as possible instead of relying on the verbose default one (e.g. https://github.com/Dabz/kafka-security-playbook/blob/master/kerberos/kafka/server.properties)
```

current server.properties is simple and small. Can you explain a bit more?

**Comment by purbon** [comment]
- [x] use CP 5.5
- [x]  add readme 

updated.

**Comment by Dabz** [comment]
> current server.properties is simple and small. Can you explain a bit more?

Actually yeah, it's quite small & simple indeed. I looked too quickly and I thought it was the whole RPM default server.properties file ;)

The PR looks good, let me merge it. 
Thanks a lot @purbon!

**Pull request merged**
