### PR TITLE
 Helper scripts to build CA

### PR DESCRIPTION
**Pull request by purbon**
Collection of helper scripts used to build the certs for #9, hopefully this is useful as helper scripts to generate this sort of CA setup. 

This scripts include tooling to create the CRL list, manage the intermediate CA (for example one used company wise), etc. It could be extended later on as well to include OCSP (https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) when need.

My main idea with this scripts is to enable a generalisation that we can use for either the TLS examples, but as well within the LDAP and other SSL related examples. As well this will enable us to just generate a CA, and use for any new case.

This scripts include parameters such as:

* CA location, useful to locate the generated scripts anywhere.
* Certs and Stores passwords.
* ...

What do you think?

### CODE REVIEW

**Comment by purbon** [comment]
Hi @sknop and @Dabz , thanks a lot for your review, I just updated this PR with:

* A readme, hopefully easy to understand.
* I added default passwords for the certs generated, so less asking to the end user.
* fix the absolute paths (my failure), all path are relative now.

what do you think?

**Comment by Dabz** [comment]
Some comments from my side:
- There are some bugs on the `build-intermediate-ca.sh`, you do a `cd intermediate` and then you always specify the directory in your command, I got plenty of exception like: `chmod: cannot access 'intermediate/certs/intermediate.cert.pem': No such file or directory`
- We should probably avoid doing a `cd` in the main script. Maybe relying on a sub-shell could be better `(cd $ca_bla; my_function_wrapping_the_code`). 
- Instead of doing `mkdir`, better to rely on `mkdir -p`. This to create subdirectory and avoid error messages
- In a general way, there seems to be a lot of confusion in the folder, sometime you do a `cd intermediate` but then you re-specify the folder in all the command `openssl x509 -noout -text -in intermediate/certs/$HOSTNAME.cert.pem`, maybe it could be better to rely on only absolute path?

**Comment by purbon** [comment]
Hi @Dabz
 I finally got time to do some work here and most necessary cleaning

what do you think?

```
There are some bugs on the build-intermediate-ca.sh, you do a cd intermediate and then you always specify the directory in your command, I got plenty of exception like: chmod: cannot access 'intermediate/certs/intermediate.cert.pem': No such file or directory
```

this is due to the fact that in the version you tested, the password was not clearly passed along. Now this is fix and the path are correct always as expected as well.

```
We should probably avoid doing a cd in the main script. Maybe relying on a sub-shell could be better (cd $ca_bla; my_function_wrapping_the_code).
Instead of doing mkdir, better to rely on mkdir -p. This to create subdirectory and avoid error messages
```
this is a good idea, done like this now.

```
In a general way, there seems to be a lot of confusion in the folder, sometime you do a cd intermediate but then you re-specify the folder in all the command openssl x509 -noout -text -in intermediate/certs/$HOSTNAME.cert.pem, maybe it could be better to rely on only absolute path?
```
half disagree here, all structures from the CA and the Intermediate CA are clear. I hope now with the restructuring is all more clear.

What do you think? all good for you to be merged?

**Comment by Dabz** [comment]
Looks good to me - let me merge

**Pull request merged**
