### PR TITLE
WIP - Kerberos cluster

### PR DESCRIPTION
**Pull request by petersilverwood**
@Dabz would really appreciate your feedback on this PR. I've taken your single broker / zk version and tried to make it a bit clearer what needs to be configured up, then expanded to a full cluster. If the revised docs / comments / config make sense I was thinking about applying them back to the single node kerberos/  build too?

### CODE REVIEW

**Comment by Dabz** [comment]
Tested locally, works like a charm ;)

**Comment by Dabz** [comment]
Maybe it would be nice to have examples in the output of ./up on how to use the kafkacat images though :thinking:

**Comment by Dabz** [comment]
This PR is not required now that you opened the new PR. 
Can I close it @petersilverwood ?

**Comment by petersilverwood** [comment]
@dabz - yes, please close.

**Pull request closed without merging**
